version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(deps)"
    ignore:
      - dependency-name: "actions/*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Android Gradle
  - package-ecosystem: "gradle"
    directory: "/VachanamAndroid"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "android(deps)"
