//
//  AnnotationExporter.swift
//  Vachanam
//
//  Exports document notes, text boxes, shapes, and annotations into clean Markdown or Plain Text.
//

import Foundation

public class AnnotationExporter {
    public static func exportToMarkdown(documentTitle: String, stickyNotes: [StickyNoteAnnotation], textBoxes: [TextBoxAnnotation], shapes: [ShapeAnnotation], bookmarks: [Bookmark]) -> String {
        var md = "# Reading Notes & Annotations: \(documentTitle)\n\n"
        md += "*Generated by Vachanam on \(DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .short))*\n\n"
        md += "---\n\n"
        
        if !bookmarks.isEmpty {
            md += "## 📌 Bookmarks\n\n"
            for b in bookmarks.sorted(by: { $0.pageIndex < $1.pageIndex }) {
                let title = b.pageTitle.isEmpty ? "Page \(b.pageIndex + 1)" : b.pageTitle
                md += "- **Page \(b.pageIndex + 1)**: \(title)\n"
                if let note = b.note, !note.isEmpty {
                    md += "  > \(note)\n"
                }
            }
            md += "\n"
        }
        
        if !stickyNotes.isEmpty {
            md += "## 📝 Sticky Notes\n\n"
            for note in stickyNotes.sorted(by: { $0.pageIndex < $1.pageIndex }) {
                md += "### Page \(note.pageIndex + 1)\n"
                md += "\(note.content)\n\n"
            }
        }
        
        if !textBoxes.isEmpty {
            md += "## 💬 Typed Comments\n\n"
            for box in textBoxes.sorted(by: { $0.pageIndex < $1.pageIndex }) {
                md += "- **Page \(box.pageIndex + 1)**: \(box.text)\n"
            }
            md += "\n"
        }
        
        if !shapes.isEmpty {
            md += "## 📐 Geometric Callouts\n\n"
            for shape in shapes.sorted(by: { $0.pageIndex < $1.pageIndex }) {
                md += "- **Page \(shape.pageIndex + 1)**: \(shape.shapeType.rawValue) callout\n"
            }
            md += "\n"
        }
        
        return md
    }
}
